name: "ExternalFavicon"

exports: "ExternalFavicon.js"

author: "subhaze"

category: "Interface"

tags: "[navigation, interface]"

demo: ""

current: "v1.4b"

sources:
  - "Source/Mootools-External-Favicon.js"