name: "ExternalFavicon"

exports: "ExternalFavicon.js"

author: "subhaze"

category: "Interface"

tags: "[navigation, interface]"

demo: "http://jsfiddle.net/FZkbt/"

current: "v1.4"

sources:
  - "Source/Mootools-External-Favicon.js"