name: "ExternalFavicon"

exports: "ExternalFavicon.js"

author: "subhaze"

category: "Interface"

tags: "[navigation]"

demo: "http://mootools.net/shell/CmHTr/41/"

current: "v1.3"

sources:
  - "Source/Mootools-External-Favicon.js"