name: "ExternalFavicon"

exports: "ExternalFavicon.js"

author: "subhaze"

category: "Interface"

tags: "[navigation]"

demo: "http://mootools.net/shell/CmHTr/40/"

current: "v1.2.1"

sources:
  - "Source/Mootools-External-Favicon.js"