name: "ExternalFavicon"

exports: "ExternalFavicon.js"

author: "subhaze"

category: "Interface"

tags: "[navigation, interface]"

demo: "http://www.jsfiddle.net/subhaze/hz9x2/"

current: "v1.4"

sources:
  - "Source/Mootools-External-Favicon.js"